import { ProductCreateManyInput } from "@/lib/generated/prisma/models";

type simpleDataType = {
  title: string;
  products: ProductCreateManyInput[];
};
const simpleData: simpleDataType = {
  title: "商品列表",
  products: [
    {
      name: "女款夏季新款時尚優雅休閒高低下擺蝴蝶結領口無袖上衣",
      slug: "女款夏季新款時尚優雅休閒高低下擺蝴蝶結領口無袖上衣",
      category: "无袖上衣",
      description: "女款无袖上衣",
      images: ["/simpleImages/pd1.webp"],
      price: "89.99",
      brand: "Franclia",
      rating: "4.3",
      stock: 1023,
      numReviews: 100,
      isFeatured: true,
      banner: "",
    },
    {
      name: "SHEIN 女士花卉印花荷叶边休闲百搭日常衬衫",
      slug: "SHEIN 女士花卉印花荷叶边休闲百搭日常衬衫",
      category: "衬衫",
      description: "SHEIN 女士花卉印花荷叶边休闲百搭日常衬衫",
      images: ["/simpleImages/pd2.webp"],
      price: "89.99",
      brand: "SHEIN",
      rating: "4.5",
      stock: 100,
      numReviews: 1020,
      isFeatured: true,
      banner: "",
    },
    {
      name: "Franclia 女士春夏新款荷叶边印花衬衫",
      slug: "Franclia 女士春夏新款荷叶边印花衬衫",
      category: "衬衫",
      description: "Franclia 女士春夏新款荷叶边印花衬衫",
      images: ["/simpleImages/pd3.webp"],
      price: "59.99",
      brand: "Franclia",
      rating: "4.5",
      stock: 100,
      numReviews: 110,
      isFeatured: true,
      banner: "",
    },
    {
      name: "Franclia 女士植物印花圆领休闲系带衬衫",
      slug: "Franclia 女士植物印花圆领休闲系带衬衫",
      category: "衬衫",
      description: "Franclia 女士植物印花圆领休闲系带衬衫",
      images: ["/simpleImages/pd4.webp"],
      price: "89.99",
      brand: "Franclia",
      rating: "4.2",
      stock: 100,
      numReviews: 100,
      isFeatured: true,
      banner: "",
    },
    {
      name: "Franclia 优雅荷叶边领带衬衫，适合通勤",
      slug: "Franclia 优雅荷叶边领带衬衫，适合通勤",
      category: "衬衫",
      description: "Franclia 优雅荷叶边领带衬衫，适合通勤",
      images: ["/simpleImages/pd4.webp"],
      price: "119.99",
      brand: "Franclia",
      rating: "4.0",
      stock: 10,
      numReviews: 10,
      isFeatured: true,
      banner: "",
    },
    {
      name: "EMERY ROSE 女士梭织休闲假日夏季衬衫",
      slug: "EMERY ROSE 女士梭织休闲假日夏季衬衫",
      category: "衬衫",
      description: "EMERY ROSE 女士梭织休闲假日夏季衬衫",
      images: ["/simpleImages/pd1.webp"],
      price: "129.99",
      brand: "EMERY ROSE",
      rating: "4.6",
      stock: 100,
      numReviews: 190,
      isFeatured: true,
      banner: "",
    },
  ],
};

export default simpleData;
